---
- hosts: all
  become: yes
  tasks:
  - name: i want to ping
    ping:

  - name: i want to install web server
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: i want to  start service 
    service:
     name: apache2
     state: started
    